# permit over-write of files
unset noclobber

# set depth of command history
setenv savehist "1000 merge lock"
setenv histfile "~/.history"

# set a useful prompt
set prompt="%m %c %h> "

# set up access to local installs
if ( -d $HOME/local/lib ) then
  setenv LD_LIBRARY_PATH "${HOME}/local/lib:${LD_LIBRARY_PATH}"
endif
if ( -d $HOME/local/bin ) then
  setenv PATH "${HOME}/local/bin:${PATH}"
endif

# bind ctrl-<arrow> keys in useful ways
bindkey '^[[5A' history-search-backward
bindkey '^[[5B' history-search-forward
bindkey '^[[5D' backward-word
bindkey '^[[5C' forward-word
bindkey '^[[1;5A' history-search-backward
bindkey '^[[1;5B' history-search-forward
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

# load history
history -L

