# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/bashrc.pre.bash" ]] && builtin source "$HOME/.fig/shell/bashrc.pre.bash"
if [ -d "$HOME/.fig" ] ; then
  # Fig pre block. Keep at the top of this file.
  . "$HOME/.fig/shell/bashrc.pre.bash"
fi
# Save the base part of the hostname. Used to run host-specific scripts
export HOSTNAME_TRIMMED=`hostname | cut -f1 -d'.' | tr '[:upper:]' '[:lower:]'`

# Set useful variables
set sq="'"
set dq='"'

# Determine whether this is an interactive shell. If not, we skip a lot of setup
case $- in
    *i*)    export RUSS_INTERACTIVE=TRUE
    ;;
esac

# Make history more useful
export HISTCONTROL=erasedups
export HISTFILESIZE=5000
export HISTSIZE=5000

# Example of testing for interactive mode
#if [ "$RUSS_INTERACTIVE" = "TRUE" ]; then
#  echo "BASHRC"
#fi

# Call OS-specific bashrc
if [ -f ~/dotfiles/bash/os/$OSTYPE.sh ]; then
  source ~/dotfiles/bash/os/$OSTYPE.sh
fi

# Call host-specific bashrc. Files ending in "_local" don't get committed to github
if [ -f ~/dotfiles/bash/host/$HOSTNAME_TRIMMED.sh ]; then
  source ~/dotfiles/bash/host/$HOSTNAME_TRIMMED.sh
elif [ -f ~/dotfiles/bash/host/${HOSTNAME_TRIMMED}_local.sh ]; then
  source ~/dotfiles/bash/host/${HOSTNAME_TRIMMED}_local.sh
fi

# Call domain-specific bashrc. Files ending in "_local" don't get committed to github
# This can be disabled on a host-by-host basis (for instance, some VMs take a long time to
#     time out on returning an empty domain). Disable by setting DOMAINNAME_TRIMMED in the
#     host-specific file.
if [ -z ${DOMAINNAME_TRIMMED+x} ]; then
  export DOMAINNAME_TRIMMED=`hostname -f | cut -f1 -d'.' --complement | tr '[:upper:]' '[:lower:]'`
fi
if [ -f ~/dotfiles/bash/domain/$DOMAINNAME_TRIMMED.sh ]; then
  source ~/dotfiles/bash/domain/$DOMAINNAME_TRIMMED.sh
elif [ -f ~/dotfiles/bash/domain/${DOMAINNAME_TRIMMED}_local.sh ]; then
  source ~/dotfiles/bash/domain/${DOMAINNAME_TRIMMED}_local.sh
fi

# Call local (non-git-committed) bashrc
if [ -f ~/dotfiles/bash/local.sh ]; then
  source ~/dotfiles/bash/local.sh
fi

# Function to ping with a datestamp
function dateping() {
  ping $1 $2 $3 $4 $5 | perl -nle 'print scalar(localtime), " ", $_'
}

# User specific environment and startup programs

PATH=$PATH:$HOME/bin
export PATH

# Define useful aliases
alias h=history
alias ls='ls $RUSS_LS_OPTS'
alias ll='ls -l'
alias startvnc='vncserver -geometry 1600x1000 :22'
alias startvncbig='vncserver -geometry 2400x1350 :22'
alias stopvnc='vncserver -kill :22'
alias g='gvim'
alias gt='gvim --remote-tab-silent'
alias filetree="\ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'"
alias dirs='dirs -v'

if [ -d "$HOME/.fig" ] ; then
  # Fig post block. Keep at the bottom of this file.
  . "$HOME/.fig/shell/bashrc.post.bash"
fi

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/bashrc.post.bash" ]] && builtin source "$HOME/.fig/shell/bashrc.post.bash"
