# .bash_profile

# Get the aliases and functions
if [ -f ~/dotfiles/bash/bashrc ]; then
        . ~/dotfiles/bash/bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH

