export HOSTNAME_TRIMMED=`hostname | cut -f1 -d'.'`

if [ -f ~/dotfiles/bash/os/$OSTYPE.sh ]; then
  source ~/dotfiles/bash/os/$OSTYPE.sh
fi

if [ -f ~/dotfiles/bash/host/$HOSTNAME_TRIMMED.sh ]; then
  source ~/dotfiles/bash/host/$HOSTNAME_TRIMMED.sh
fi

# Define useful aliases
alias h=history
alias ls='ls $RUSS_LS_OPTS'
alias ll='ls -l'
alias startvnc='vncserver -geometry 2400x1350 :22'
alias stopvnc='vncserver -kill :22'
alias g='gvim'
alias gt='gvim --remote-tab-silent'

