# .bash_profile

# Get the aliases and functions
if [ -f ~/dotfiles/bash/bashrc ]; then
  . ~/dotfiles/bash/bashrc
fi


# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
  PATH="$HOME/bin:$PATH"
fi

# Setting PATH for Python 3.8 (is this for Fig?)
# The original version is saved in .bash_profile.pysave
if [ -d "/Library/Frameworks/Python.framework/Versions/3.8/bin" ] ; then
  PATH="/Library/Frameworks/Python.framework/Versions/3.8/bin:${PATH}"
fi
export PATH
